<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>eu.ajg.fairdistribution</groupId>
	<artifactId>FairStudentDistribution</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Fair Student Distribution Calculator</name>
	<properties>
		<src.dir>src/main/java</src.dir>
	</properties>
	<build>
		<sourceDirectory>${src.dir}</sourceDirectory>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>21</release>
				</configuration>
			</plugin>
			<plugin>
			  <artifactId>maven-assembly-plugin</artifactId>
			  <configuration>
				<archive>
				  <manifest>
					<mainClass>eu.ajg.fairdistribution.Main</mainClass>
				  </manifest>
				</archive>
				<descriptorRefs>
				  <descriptorRef>jar-with-dependencies</descriptorRef>
				</descriptorRefs>
			  </configuration>
			  <executions>
				<execution>
				  <id>make-assembly</id>
				  <phase>package</phase>
				  <goals>
					<goal>single</goal>
				  </goals>
				</execution>
			  </executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>org.choco-solver</groupId>
			<artifactId>choco-solver</artifactId>
			<version>4.10.18</version>
		</dependency>
	</dependencies>
</project>